Add reservation
Lucas-Erkana/BookFlix-Frontend pull request #18
Opened 2023-07-27 12:35 UTC by SamTush

2023-07-27 15:38 UTC, torobucci requested changes
# STATUS : Changes Required ♻️

Hi @SamTush   😃, 

You've really done a great work, I must confess!

There are some issues I would like to point out to improve your project.

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425615-8927e377-c543-407b-8da4-5c09fecc261b.gif)

## Highlights
- Proper display of Reserve Form✔️
- Greate design of user reservations ✔️ 
- User name is prefilled when navigating to reserve form ✔️ 

## Changes Required

- ### Kindly ensure your `feature/reservation` branch is up to date with the dev branch. Currently its `2 commits behind the dev`.

![Capture](https://github.com/Lucash2022/BookFlix-Frontend/assets/103370560/4807d1eb-e7f0-4b04-ae14-0e3175690cdf)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-07-27 15:38 UTC, torobucci commented on src/components/view/ReservationForm.js
> +import { fetchServices } from '../../redux/ServicesSlice';
- [ ] Kindly Update the `fetchServices` to `fetchMovies` since in the `dev` branch there exists  `fetchMovies` redux thunk.

2023-07-27 15:38 UTC, torobucci commented on src/components/view/ReservationForm.js
> +  const services = useSelector((state) => state.services.services);
- [ ] Kindly use `const services = useSelector((state) => state.movies.movies)` since we changed the name of our `MovieSlice initialState`  to movies

2023-07-27 15:38 UTC, torobucci commented on src/components/view/Reservations.js
> +import { fetchServices } from '../../redux/ServicesSlice';
- [ ] Similarly here update `fetchServices` to `fetchMovies`

2023-07-27 15:38 UTC, torobucci commented on src/components/view/Reservations.js
> +  const services = useSelector((state) => state.services.services);
- [ ]  Kindly use `const services = useSelector((state) => state.movies.movies) ` since we changed the name of our `MovieSlice initialState` to movies

2023-07-27 15:41 UTC, torobucci commented on src/redux/ServicesSlice.js
> +// ServiceSlice
- [ ] Since since this file isn't useable you can delete it

2023-07-28 07:34 UTC, SamTush commented on src/redux/ServicesSlice.js
> +// ServiceSlice
Thank you. I think we shall have a linter error if the file is deleted

2023-07-28 09:48 UTC, torobucci approved these changes
## Status: Approved :heavy_check_mark:

Hi @SamTush , 👋 👋  

Your project is complete! Great job for following the project requirement🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif" width="600px" height="300px">

## Good Points 👍

- Make changes required ✔️

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @torobucci  in your question so I can receive the notification.

2023-07-28 10:11 UTC, merged